config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#show'
  get 'auth/:provider/callback', to: 'users#new'
  resources :passwords,
    controller: 'clearance/passwords',
    only: [:create, :new]

  resource :session,
    controller: 'clearance/sessions',
    only: [:create]

  resources :users,
    controller: 'users',
    only: Clearance.configuration.user_actions do
      resource :password,
        controller: 'clearance/passwords',
        only: [:create, :edit, :update]
    end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'

  if Clearance.configuration.allow_sign_up?
    get '/sign_up' => 'clearance/users#new', as: 'sign_up'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  validates :auth_provider, :auth_uid, :hattrick_username,
    :oauth_token, :oauth_secret, presence: true

  def self.from_omniauth(auth)
    where(auth_provider: auth.provider, auth_uid: auth.uid).first_or_initialize.tap do |user|
      user.hattrick_username = auth.info.username
      user.oauth_token = auth.credentials.token
      user.oauth_secret = auth.credentials.secret
    end
  end
  
  def hattruby_client
    @hattruby_client ||= Hattruby::Client.new(
      consumer_key: ENV['HATTRICK_KEY'],
      consumer_secret: ENV['HATTRICK_SECRET'],
      token: oauth_token,
      token_secret: oauth_secret
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  #before_action :require_login, :authorize
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def show
  end

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def new
    @user = User.from_omniauth(env['omniauth.auth'])
    render template: "users/new"
  end

  private

  def user_params
    params.require(:user).permit(:auth_provider, :auth_uid, :email,
                                 :hattrick_username, :oauth_token,
                                 :oauth_secret, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/show.html.erb
<h1>Hattrick England Tracker</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HattrickEnglandTracker</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= link_to "Sign up", "/auth/hattrick" %>
    <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>


    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>
    <%= form.hidden_field :hattrick_username %>
    <%= form.hidden_field :auth_provider %>
    <%= form.hidden_field :auth_uid %>
    <%= form.hidden_field :oauth_token %>
    <%= form.hidden_field :oauth_secret %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>